name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # Install dependencies, lint, test and build projects if any of these fail the whole pipepine is failed
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: application
          path: app.exe
