name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn  lint
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: application
          path: app.exe
